login error message update
LaiTeam2021/EchoWallApp pull request #14
Opened 2021-04-01 02:53 UTC by TFDU

![image](https://user-images.githubusercontent.com/46980693/113236721-6ea2f600-9273-11eb-806e-7c5a6785a987.png)
problem: Do we have to observe the email and password in real time and check it? which means when the user is editing email, error message is being showed(when invalid email) even if user hasn't click on login button.

2021-04-02 19:24 UTC, jingweihu requested changes
sounds like we need to merge the error messages to just one instead of showing them individually. In this case I would recommend put an error message above SIGN IN button and have a shaking animation

2021-04-02 19:24 UTC, jingweihu commented on app/src/main/java/com/laiteam/echowall/ui/onboarding/login/LoginFragment.kt
> +private const val DEFAULT_INVALID_EMAIL_ERROR_MESSAGE = "Invalid email"
put them in the string.xml for i18

2021-04-02 22:06 UTC, TFDU commented
1, put error message above SIGN IN button
2, add animation
3, add error message Strings in values
4, [PROBLEM] cannot get references of Strings in values with getString() or getText(), hard-code String still remains in the code

2021-04-24 22:44 UTC, jingweihu approved these changes

2021-04-24 22:44 UTC, merged